name: study_planner_ai
description: Study Planner with Calendar & AI Suggestions
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter



    

  cupertino_icons: ^1.0.6

  # State management
  provider: ^6.0.5

  # Firebase & Firestore
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  firebase_messaging: ^15.0.0

  # Local DB (Offline mode)
  sqflite: ^2.3.0
  path_provider: ^2.1.3

  # Calendar UI
  # Calendar UI
  table_calendar: ^3.1.2
  percent_indicator: ^4.2.3
  google_fonts: ^8.0.2
  fl_chart: ^0.66.0

  # Animations & Lottie
  lottie: ^3.1.0

  # QR / Barcode scanning
  mobile_scanner: ^5.1.0

  # Voice assistant
  speech_to_text: ^6.6.0
  flutter_tts: ^4.0.2

  # Notifications
  flutter_local_notifications: ^17.0.0

  # Ultra UI & Animations
  flutter_animate: ^4.5.2
  simple_animations: ^5.0.2

  # AI
  google_generative_ai: ^0.4.7

  # Preferences
  shared_preferences: ^2.2.3

  # Intl / dates
  intl: ^0.19.0

  uuid: ^4.4.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.0.0
  image_picker: ^1.2.1
  firebase_storage: ^12.4.10
  cached_network_image: ^3.3.1



flutter:
  uses-material-design: true

  assets:
    - assets/lottie/splash.json
    - assets/lottie/empty_state.json
    - assets/lottie/study_mode.json
dev_dependencies:
  flutter_test:
    sdk: flutter

